name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: astral-sh/setup-uv@eb1897b8dc4b5d5bfe39a428a8f2304605e0983c # v7.0.0
        with:
          enable-cache: true
          python-version: "3.13"
      - run: uv sync --locked --all-groups
      - run: uv run pytest
      - run: uv run ruff check .
      - run: uv run ruff format --check .
      - run: uv run mypy
